name: lint
on:
  pull_request:
  push:
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies (ubuntu)
        id: install-deps-ubuntu
        run: |
          sudo apt-get install -y clang-format

      - name: Lint
        run: clang-format --dry-run -Werror *.cpp
